application: p2ppostal
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .+/
  script: slashmurderer.application

- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /apple-touch-icon\.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon\.png

- url: /apple-touch-icon-precomposed\.png
  static_files: static/apple-touch-icon-precomposed.png
  upload: static/apple-touch-icon-precomposed\.png

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

# coupon code
- url: /c/.*
  script: main.app
  secure: always

# coupon code
- url: /d/.*
  script: main.app
  secure: always

- url: /pay/.*
  script: main.app
  secure: always

- url: /checkout/.*
  script: main.app
  secure: always

- url: /res/.*
  script: main.app
  secure: always

- url: /.*
  script: main.app


- url: /_ah/mail/.+
  script: Utils.EmailUtils.app
#  login: admin

builtins:
- remote_api: on

inbound_services:
- mail

libraries:
- name: jinja2
  version: latest

#error_handlers:
#  - error_code: over_quota
#    file: over_quota.html
